### ISSUE TITLE
Occasional "database item already exists" errors when instantiating timesketch_timesketch and timesketch_worker images

### ISSUE THREAD

**Issue by john-corcoran** [ilyaglow/docker-timesketch#3]
When instantiating the timesketch_timesketch and timesketch_worker images, occasional errors are raised in the postgres, timesketch_timesketch and timesketch_worker containers informing that items in the database already exist.

Adding a sleep statement to the worker clause in docker-entrypoint.sh seems to mitigate the issue:
elif [ "$1" = 'worker' ]; then
	sleep 10
	prepare
	exec 'celery -A timesketch.lib.tasks worker --uid nobody --autoscale=10,1 --loglevel=info'

Here's an example of the errors:
postgres_1       | ERROR:  relation "timeline" already exists
postgres_1       | STATEMENT:  
postgres_1       | 	CREATE TABLE timeline (
postgres_1       | 		id SERIAL NOT NULL, 
postgres_1       | 		created_at TIMESTAMP WITHOUT TIME ZONE, 
postgres_1       | 		updated_at TIMESTAMP WITHOUT TIME ZONE, 
postgres_1       | 		name VARCHAR(255), 
postgres_1       | 		description TEXT, 
postgres_1       | 		color VARCHAR(6), 
postgres_1       | 		user_id INTEGER, 
postgres_1       | 		searchindex_id INTEGER, 
postgres_1       | 		sketch_id INTEGER, 
postgres_1       | 		PRIMARY KEY (id), 
postgres_1       | 		FOREIGN KEY(user_id) REFERENCES "user" (id), 
postgres_1       | 		FOREIGN KEY(searchindex_id) REFERENCES searchindex (id), 
postgres_1       | 		FOREIGN KEY(sketch_id) REFERENCES sketch (id)
postgres_1       | 	)
postgres_1       | 	
postgres_1       | 	
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/bin/celery", line 11, in <module>
worker_1         |     sys.exit(main())
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
worker_1         |     _main()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
worker_1         |     cmd.execute_from_commandline(argv)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
worker_1         |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 279, in execute_from_commandline
worker_1         |     argv = self.setup_app_from_commandline(argv)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
worker_1         |     self.app = self.find_app(app)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 503, in find_app
worker_1         |     return find_app(app, symbol_by_name=self.symbol_by_name)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 358, in find_app
worker_1         |     sym = imp(app)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
worker_1         |     return imp(module, package=package)
worker_1         |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
worker_1         |     __import__(name)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 36, in <module>
worker_1         |     celery = create_celery_app()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 193, in create_celery_app
worker_1         |     app = create_app()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 103, in create_app
worker_1         |     db = init_db()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/timesketch/models/__init__.py", line 55, in init_db
worker_1         |     BaseModel.metadata.create_all(bind=engine)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3949, in create_all
worker_1         |     tables=tables)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
worker_1         |     conn._run_visitor(visitorcallable, element, **kwargs)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
worker_1         |     **kwargs).traverse_single(element)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker_1         |     return meth(obj, **kw)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
worker_1         |     _is_metadata_operation=True)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
worker_1         |     return meth(obj, **kw)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
worker_1         |     include_foreign_key_constraints=include_foreign_key_constraints
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
worker_1         |     return meth(self, multiparams, params)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
worker_1         |     return connection._execute_ddl(self, multiparams, params)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
worker_1         |     compiled
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
worker_1         |     context)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
worker_1         |     exc_info
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker_1         |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
worker_1         |     context)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
worker_1         |     cursor.execute(statement, parameters)
worker_1         | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "timeline" already exists
worker_1         |  [SQL: '\nCREATE TABLE timeline (\n\tid SERIAL NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tname VARCHAR(255), \n\tdescription TEXT, \n\tcolor VARCHAR(6), \n\tuser_id INTEGER, \n\tsearchindex_id INTEGER, \n\tsketch_id INTEGER, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES "user" (id), \n\tFOREIGN KEY(searchindex_id) REFERENCES searchindex (id), \n\tFOREIGN KEY(sketch_id) REFERENCES sketch (id)\n)\n\n']
postgres_1       | ERROR:  relation "event_label" already exists
postgres_1       | STATEMENT:  
postgres_1       | 	CREATE TABLE event_label (
postgres_1       | 		id SERIAL NOT NULL, 
postgres_1       | 		created_at TIMESTAMP WITHOUT TIME ZONE, 
postgres_1       | 		updated_at TIMESTAMP WITHOUT TIME ZONE, 
postgres_1       | 		label VARCHAR(255), 
postgres_1       | 		parent_id INTEGER, 
postgres_1       | 		user_id INTEGER, 
postgres_1       | 		PRIMARY KEY (id), 
postgres_1       | 		FOREIGN KEY(parent_id) REFERENCES event (id), 
postgres_1       | 		FOREIGN KEY(user_id) REFERENCES "user" (id)
postgres_1       | 	)
postgres_1       | 	
postgres_1       | 	
timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/local/bin/tsctl", line 430, in <module>
timesketch_1     |     shell_manager.run()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
timesketch_1     |     result = self.handle(sys.argv[0], sys.argv[1:])
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
timesketch_1     |     res = handle(*args, **config)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 156, in __call__
timesketch_1     |     app = app(**kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 103, in create_app
timesketch_1     |     db = init_db()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/models/__init__.py", line 55, in init_db
timesketch_1     |     BaseModel.metadata.create_all(bind=engine)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3949, in create_all
timesketch_1     |     tables=tables)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
timesketch_1     |     conn._run_visitor(visitorcallable, element, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
timesketch_1     |     **kwargs).traverse_single(element)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
timesketch_1     |     return meth(obj, **kw)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
timesketch_1     |     _is_metadata_operation=True)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
timesketch_1     |     return meth(obj, **kw)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
timesketch_1     |     include_foreign_key_constraints=include_foreign_key_constraints
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
timesketch_1     |     return meth(self, multiparams, params)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
timesketch_1     |     return connection._execute_ddl(self, multiparams, params)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
timesketch_1     |     compiled
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
timesketch_1     |     context)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
timesketch_1     |     exc_info
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
timesketch_1     |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
timesketch_1     |     context)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
timesketch_1     |     cursor.execute(statement, parameters)
timesketch_1     | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "event_label" already exists
timesketch_1     |  [SQL: '\nCREATE TABLE event_label (\n\tid SERIAL NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tlabel VARCHAR(255), \n\tparent_id INTEGER, \n\tuser_id INTEGER, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(parent_id) REFERENCES event (id), \n\tFOREIGN KEY(user_id) REFERENCES "user" (id)\n)\n\n']

**Comment by ilyaglow** [comment]
Thanks for filling an issue! Unfortunately I can't reproduce this. Could this error happen because of worker container starts faster than timesketch in a kind of race condition? 

What if `sleep 10` before prepare function will be `sleep 5`? Will the problem persist?

**Comment by john-corcoran** [comment]
It only happens occasionally to me so agreed that it's hard to reproduce! Anecdotally it seems to happen more often when memory is constrained on the host: for a VM with 4GB memory it happens frequently, while for a VM with 8GB memory it's rare.

Using a `sleep 5` or even a `sleep 1` before the prepare function also seems to address the issue.

**Comment by ilyaglow** [comment]
Okay, I'm going to fix this.

**Comment by ilyaglow** [comment]
Hope the problem is resolved now. Reopen if it's not.
