### ISSUE TITLE
COPY failed: docker-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by maestretti** [ilyaglow/docker-timesketch#8]
I got this error on the main line version as well. I can attach to the container with bash and see the file and copy it but the COPY command is failing for some reason. 

```
Removing intermediate container 54f567e84dd0
Step 4/8 : COPY docker-entrypoint.sh /
COPY failed: stat /var/lib/docker/tmp/docker-builder998059328/docker-entrypoint.sh: no such file or directory
```

I can run bash and see it. And copy it from there. I tried adding the full path to your Dockerfile but no luck with that either. 

```
root@774c57060e8f:/# ls /usr/local/src/timesketch/docker/
Dockerfile  README.md  docker-compose.yml  docker-entrypoint.sh
```

This is on Docker for Mac. 

Even once I copy it over and patch up the entrypoint etc I get a different error but that seems to be related to the graph functionality so I will address that with the main line. Just wanted to share here as you Dockerfile looks further along.

**Comment by ilyaglow** [comment]
That is weird. Probably something Mac-related, because I've just successfully built this image on [docker hub](https://hub.docker.com/r/ilyaglow/timesketch/builds/b44sdqofvbx5mknbumjicnj/).
